version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run test
      - npm run cdk synth -- -o dist

reports:
  stack-tests:
    files:
      - jest-junit.xml
    base-directory: test_reports
    file-format: JunitXml

artifacts:
  base-directory: dist
  files:
    - VirtualWallStack.template.json

cache:
  paths:
    - 'node_modules/**/*'