version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run cdk synth -- -o dist

artifacts:
  base-directory: dist
  files:
    - VirtualWallStack.template.json

cache:
  paths:
    - 'node_modules/**/*'